version: '2.1.2.{build}'

# add nuget api to hosts file, making sure we can actually nuget restore for the build
hosts:
  api.nuget.org: 93.184.221.200

# enforce crlf fixing
init:
  git config --global core.autocrlf true
# restrict how much history we try to grab
clone_depth: 3
# ignore a certain subset of files when evaluating build-changes
skip_commits:
  files:
  - docs/*
  - '**/*.md'
  #- '**/*.yml'
  - license
  - License.rtf
branches:
  only:
  - master
  - staging
  - next
skip_tags: true

# build-matrix: all Release CPUs on VS2017
image: Visual Studio 2017
configuration: Release
platform: Any CPU

# cache the nuget packages unless something changed there
cache:
  - packages/ -> **/packages.config


#install:
#  set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%
assembly_info:
  patch: true
  file: RetailCoder.VBE\Properties\AssemblyInfo.cs
  assembly_version: '{version}'

before_build:
  cinst innosetup
build:
  verbosity: detailed

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
